language: c

sudo: false

env:
  global:
    - LUAROCKS_VERSION="2.4.1"
    - ROCK_NAME="talents"
    - ROCK_VERSION="0.1-2"
  matrix:
    - LUA_VERSION="5.1.1"       LUA_SUFFIX=""    REBUILD=1 NOCOVERAGE=0
    - LUA_VERSION="5.1.4"       LUA_SUFFIX=""    REBUILD=1 NOCOVERAGE=0
    - LUA_VERSION="5.2.4"       LUA_SUFFIX=""    REBUILD=1 NOCOVERAGE=0
    - LUA_VERSION="5.2.1"       LUA_SUFFIX=""    REBUILD=1 NOCOVERAGE=0
    - LUA_VERSION="5.3.1"       LUA_SUFFIX=""    REBUILD=1 NOCOVERAGE=0
    - LUA_VERSION="5.3.4"       LUA_SUFFIX=""    REBUILD=1 NOCOVERAGE=0
    - LUA_VERSION="5.3.6"       LUA_SUFFIX=""    REBUILD=1 NOCOVERAGE=0
    - LUA_VERSION="5.4.1"       LUA_SUFFIX=""    REBUILD=1 NOCOVERAGE=0
    - LUA_VERSION="2.0.5"       LUA_SUFFIX="jit" REBUILD=1 NOCOVERAGE=0
    - LUA_VERSION="2.1.0-beta3" LUA_SUFFIX="jit" REBUILD=1 NOCOVERAGE=0

before_install: "source .travis-ci/setup.sh"

install: "bash .travis-ci/install.sh"

script: "bash .travis-ci/test.sh"

after_success: "bash .travis-ci/report.sh"

cache:
  directories:
    - "$HOME/.travis-ci-lua"

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always
